FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ENV PORT=$PORT
ARG PORT=3500
EXPOSE $PORT

ARG NODE_ENV
ENV NODE_ENV=${NODE_ENV}

COPY ./backend-entrypoint.sh /

ENTRYPOINT ["/backend-entrypoint.sh"]
